In [8]:
import numpy as np

# mathematica style function defined
Matrix = np.array     
Eigensystem = np.linalg.eig
Conj = np.conjugate

A = Matrix([[-4, 4, -1, 9],
           [6, -6, 9, 10],
           [-5, 8, 6, 8],
           [ 7, 0, -4, -2]])

Eigenvalues, eigenvectors_tem = Eigensystem(A)

Eigenvectors = eigenvectors_tem.transpose() 

In [3]:
Eigenvalues

array([  7.91990627+3.47031997j,   7.91990627-3.47031997j,
       -13.76135877+0.j        ,  -8.07845377+0.j        ])

In [4]:
Eigenvectors

array([[-0.0091516 +0.29357931j,  0.39202769+0.23164396j,
         0.76189327+0.j        , -0.21490198+0.28234479j],
       [-0.0091516 -0.29357931j,  0.39202769-0.23164396j,
         0.76189327-0.j        , -0.21490198-0.28234479j],
       [-0.46037801+0.j        ,  0.74688832+0.j        ,
        -0.46565954+0.j        ,  0.11563357+0.j        ],
       [-0.50291592+0.j        , -0.68341441+0.j        ,
        -0.08688245+0.j        ,  0.52198828+0.j        ]])

In [5]:
np.dot(Conj(Eigenvectors[0]), Eigenvectors[0])

(1+0j)

In [6]:
len(Eigenvalues)

4

In [7]:
tem = 0.0
for i in range(len(Eigenvalues)) : 
    tem += np.dot(A, Eigenvectors[i]) - Eigenvalues[i]* Eigenvectors[i]

tem

array([ 6.66133815e-15+0.j,  4.44089210e-15+0.j, -1.46549439e-14+0.j,
        7.32747196e-15+0.j])